title: Saurabh Maydeo
description: PhD Student at UTA | Machine Learning | Healthcare | Bioinformatics
url: "https://saurabhmaydeo.github.io"
markdown: kramdown

social:
  email: SaurabhMaydeo@gmail.com
  github: saurabhmaydeo
  linkedin: your-linkedin