title: "Saurabh Maydeo"
email: "SaurabhMaydeo@gmail.com"
description: "Machine Learning, Healthcare, Bioinformatics"
baseurl: ""
url: "https://yourusername.github.io"  # Replace with your GitHub username
theme: minima
plugins:
  - jekyll-feed
